#!/bin/bash
# File not found

trap "/usr/bin/killall -q -u $USER Blotto 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15

/c/cs474/bin/run -stdout=/dev/null -stderr=/dev/null ./Blotto fnf.in win 1 2 3 4 < /dev/null
