#!/bin/bash
# Missing entry id in matchup

trap "/usr/bin/killall -q -u $USER Blotto 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15

/c/cs474/bin/run -stdout=/dev/null -stderr=/dev/null ./Blotto /c/cs223/hw4/Tests/missing_id.in win 1 2 3 4 < /c/cs223/hw4/Tests/t036.in
